modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerUrl="https://github.com/twalse/twcinematic/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
logoFile="twcinematic.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="watermedia"
    mandatory=false
    versionRange="[2.0.0,)"
    ordering="NONE"
    side="CLIENT"
